apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: celeste-lopez-e2e-assignment
  app.kubernetes.io/instance: celeste-lopez-e2e-assignment-instance
  app.kubernetes.io/name: celeste-lopez-e2e-assignment